# version: 1.0.0

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

palette = "catppuccin_macchiato"

format = """
$directory\
$fill\
$cmd_duration $jobs $git_status $git_state $git_branch $git_commit $nodejs $ruby\
$line_break\
$sudo\
$character"""

[character]
# format = "[►](bright-yellow) "
format = "[❯](bright-yellow) "

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[directory]
truncation_length = 999
truncate_to_repo = false
read_only = ""
use_os_path_sep = true
style = "bold blue"
format = '[$path ]($style)'

[fill]
symbol = '-'
style = "dimmed black"

[git_branch]
format = "[$symbol $branch]($style)"
symbol = ""
style = "bold bright-cyan"
only_attached = true

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_status]
up_to_date = ''
staged = '[++\($count\)](green)'

[ruby]
format = "[$symbol $version]($style)"
symbol = ""
style = "bold red"

[nodejs]
format = "[$symbol$version]($style)"
style = "bold green"

[sudo]
format = "[$symbol]($style)"
style = "bold bright-purple"
symbol = "⚡"
disabled = false

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
